### ISSUE TITLE
Distributable Plugin

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-derive#1]
I like this plugin very much! Do you know when you release a distributable version? I liked what Adam Barrett in https://github.com/canjs/can-util-function/tree/master/dist did

**Comment by akagomez** [comment]
This repo creates a `dist` folder for every release: https://github.com/canjs/can-derive/tree/v0.0.11/dist

It can also be installed via NPM: https://www.npmjs.com/package/can-derive

**Comment by pYr0x** [comment]
Thanks
