### ISSUE TITLE
Hot swap a predicate

### ISSUE THREAD

**Issue by akagomez** [canjs/can-derive#13]
It would be cheaper to replace/re-evaluate a predicate against every item in the list than to reconstruct the predicate/filtered tree.

**Comment by akagomez** [comment]
We'll need to come up with an API for this also.

**Comment by justinbmeyer** [comment]
What does this mean?  If you mean replace the predicate function with another one, I doubt that's necessary.  

Lets say I wanted completed items, I might have:

```js
todos.filter(function(t){
 return t.attr("completed");
});
```

If there was a situation I wanted to change these to active (not completed) todos, I shouldn't need to replace the function, instead my code should look like:

```js
todos.filter(function(t){
 if( state.attr("filter") === "completed") {
    return t.attr("completed");
 } else {
    return !t.attr("completed");
 }
});
```


this is much more inline with how CanJS is supposed to work.

**Comment by akagomez** [comment]
@justinbmeyer This is a good point. I can't think of a practical use case for this either. I was fixated on performance while explaining the internals to @jandjorgensen when the idea hit me and I jotted it down. 

Good save.
