### ISSUE TITLE
Create stache helpers

### ISSUE THREAD

**Issue by akagomez** [canjs/can-derive#5]
- [ ] Filter by index range: `{{#paginate list start=0 end=10}}`
- [ ] Filter by map property: `{{#filter list completed=true}}`

**Comment by imjoshdean** [comment]
Honestly, I'd rather we implement it INTO #each rather than make an entirely new helper.

**Comment by akagomez** [comment]
The reason I'm suggesting we break it up into separate helpers is that there are potentially many ways to filter a list that we could describe via helper. Using a `start` and `end` for pagination is only one of them.

**Comment by akagomez** [comment]
Also, the `{{#each}}` helper can take both an `object` and an `array`. Start/end will have no influence on an object. From an API perspective, the rules of `{{#each}}` become overwhelming once it accepts `start` and `end` properties.

**Comment by akagomez** [comment]
@justinbmeyer reminded me that sub-expressions handle this case pretty well already:

```
{{#each list.paginate(0,10)}}
{{#each list.filter(completed=true)}}
```
