### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by matthewp** [canjs/can-derive#6]

**Comment by akagomez** [comment]
@matthewp I switched the can-derive and can-binarytree repo's to "On" in the Travis CI console. What else do I have to do?

**Comment by matthewp** [comment]
@akagomez copy a .travis.yml from another project, like this one https://github.com/canjs/can-wait/blob/master/.travis.yml

Edit the "script" field (yours is probably just `npm test`).

**Comment by matthewp** [comment]
@akagomez ping me and we can do it together if you want.

**Comment by akagomez** [comment]
Thanks @matthewp! Turned out to be super easy. Thanks for the efficient guidance. 

First CI'd PR: https://github.com/canjs/can-derive/pull/19
