### ISSUE TITLE
Document how to use can-derive with the define plugin

### ISSUE THREAD

**Issue by akagomez** [canjs/can-derive#9]
```
{
  define: {
    todos: {
      Value: Todos
    },
    completedTodos: {
      get: function () {
        return this.attr('todos').dFilter(...); 
      }
    }
  }
}
```

**Comment by marshallswain** [comment]
:+1:

**Comment by akagomez** [comment]
The README now touches on this [in this section](https://github.com/canjs/can-derive#with-canmapdefine). 

Unfortunately @jandjorgensen and I settled on `value` instead of `get` because `get` will cause can-derive to re-filter every time the source list fires "add" or "remove" events. 

Now that I think of it though, we should be able to make `.dFilter()` use `__notObserve` internally before calling `.each()` which will ensure it's only bound to "set" events on the source list. 

I'll open a new issue.

**Comment by justinbmeyer** [comment]
It has to work with get for the reasons I talked about Monday (loading data for instance).
